version: '3'

networks:
  default:
    external:
      name: home_network

services:
  web:
    build: .
    image: minance.react:local
    container_name: minance-react
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
