name: service

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/service*.yml
      - service/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/service*.yml
      - service/**

defaults:
  run:
    working-directory: ./service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
